version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: digital_housing_db_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: digital_housing_dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - app-network

  # Backend API (Development)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    container_name: digital_housing_api_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: dev_jwt_secret_key
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./server:/app
      # - /app/node_modules
      # Note: Using Cloudinary for file storage, no local upload volume needed
    command: npm run dev

volumes:
  mongodb_dev_data:

networks:
  app-network:
    driver: bridge